# Generated by Django 4.2.3 on 2023-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('partner_name', models.CharField(max_length=100)),
            ],
        ),
    ]
